### ISSUE TITLE
Re-trigger `infoview.__update()` on LSP `ContentModified` error code? Yes.

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#108]
@gebner I noticed in the VSCode implementation that [`triggerUpdate()` is called again when receiving error code -32801 (`ContentModified`) from a plainGoal/plainTermGoal request](https://github.com/leanprover-community/vscode-lean4/blob/d5f1926be34e73af23d551be779a5b98e721e0ba/lean4-infoview/src/infoview/info.tsx#L246). I wanted to ask how exactly to bring this about? I tried to issue an `infoview.__update()` followed immediately by a `vim.api.nvim_buf_set_lines()` (which sends `textDocument/didChange`) but it looks like the changes were picked up just fine (21d9c83).

At the moment nvim [simply clears the callback on `ContentModified`](https://github.com/neovim/neovim/blob/93443d59a9680a6055d4602653d34516bc2c2571/runtime/lua/vim/lsp/rpc.lua#L540), which it classifies as "RPC internal" so if we wanted to handle this some upstream changes may be in order. Is this something we need to consider?

**Comment by gebner** [comment]
> @gebner I noticed in the VSCode implementation that [`triggerUpdate()` is called again when receiving error code -32801 (`ContentModified`) from a plainGoal/plainTermGoal request](https://github.com/leanprover-community/vscode-lean4/blob/d5f1926be34e73af23d551be779a5b98e721e0ba/lean4-infoview/src/infoview/info.tsx#L246). I wanted to ask how exactly to bring this about? I tried to issue an `infoview.__update()` followed immediately by a `vim.api.nvim_buf_set_lines()` (which sends `textDocument/didChange`) but it looks like the changes were picked up just fine ([21d9c83](https://github.com/Julian/lean.nvim/commit/21d9c83ea484f5d0c6b40a0d232bee6fdcd38b60)).

This error happens when you send the requests in quick succession.  I believe the following sequence of requests should cause this error code:
 1. Modify the file.
 2. Request a plainGoal.
 3. Modify the file (within a few milliseconds of the first request).

What will happen is that the server *queues* the first modification (we don't want to restart parsing every few milliseconds).  When the server then receives request 2, it puts it in a queue as well (to be processed after the modification).  However after request 3, the plainGoal request refers to document version that has never been parsed, so it is discarded and the ContentModified error is returned.  A few milliseconds afterwards, the server begins to parse the new file version (from request 3).

> At the moment nvim [simply clears the callback on `ContentModified`](https://github.com/neovim/neovim/blob/93443d59a9680a6055d4602653d34516bc2c2571/runtime/lua/vim/lsp/rpc.lua#L540), which it classifies as "RPC internal" so if we wanted to handle this some upstream changes may be in order. Is this something we need to consider?

Oh yeah, we should retry the request on ContentModified.

**Comment by rish987** [comment]
@gebner Thanks for the details, yes indeed I was able to cause this error using the steps you described at dcb9b27. So now it's just a matter of seeing if the folks upstream take kindly to exposing `ContentModified` to callbacks.

Classifying this as a bug since it's feasible to reproduce from a user's perspective when editing if they, for example:
1. Decrease the CursorHoldI timeout to be very short.
2. Have a hook on CursorHoldI that modifies the buffer, which happens to get called after `infoview.__update()`.

in which case the infoview just wouldn't update (because RPC would cancel the callback).
