### ISSUE TITLE
LSP method not supported errors on startup

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#177]
I often see messages like:

```
method $/lean/discoverWidget is not supported by any of the servers registered for the current buffer
```

when starting up nvim. Presumably if requests are being sent to the LSP before it's fully ready?

It will happen with similar messages mentioning one or two other language servers methods as well. Everything else works fine, and the infoview happily works as I start to edit.

**Comment by Julian** [comment]
mjlbach says this possibly is related to this change: https://github.com/neovim/neovim/pull/15926/files#diff-c6a4160a416b22cd1fd833b8f852c4fbaf1f25adf75053e82a1025aa2c607ac9R1270

(Will need to have a closer look to see why/what to do about it/whether it's here or upstream)

**Comment by gebner** [comment]
I also see this really often now (maybe because I've upgraded to 0.6.0).  I believe it happens when the infoview makes requests right after startup, before the Lean server has been initialized yet.

> mjlbach says this possibly is related to this change: https://github.com/neovim/neovim/pull/15926/files#diff-c6a4160a416b22cd1fd833b8f852c4fbaf1f25adf75053e82a1025aa2c607ac9R1270

If I read this change correctly, we can no longer handle unsupported request errors. :cry:  Which means we probably need to switch to the `vim.lsp.client` API like in the RPC code.

**Comment by Julian** [comment]
Sorry, I should have updated this with the upstream ticket (which I filed after not being able to figure this out and talking to him) -- neovim/neovim#16279

I think what we're seeing is unexpected (meaning he says these shouldn't fire, let alone somehow fire only during initialization), so there's some minor bug somewhere that needs fixing.

**Comment by mjlbach** [comment]
> If I read this change correctly, we can no longer handle unsupported request errors. 

WDYM? `client.supports_method` is always true for off-spec requests.

**Comment by gebner** [comment]
> WDYM? client.supports_method is always true for off-spec requests.

If no client is connected yet, then any method is considered unsupported afaict.

> client.supports_method is always true for off-spec requests.

I didn't realize that, but I think that means that lean.nvim is very broken if more than one client is connected.  Reading through the `lsp.lua` source code, buf_request will then call the handler once for every client (no matter whether it supports the request or not).  We wrap that function using plenary's async support, I'm not even sure what happens if the callback is executed more than once.

**Comment by mjlbach** [comment]
> If no client is connected yet, then any method is considered unsupported afaict.

Yes, this is true.

>  Reading through the lsp.lua source code, buf_request will then call the handler once for every client (no matter whether it supports the request or not). 

Yes. We handle error's but generally speaking we want to move away from the current buf_request system to something that is a lower level abstraction over client.request/request_sync which more directly handles the usecase of multiple language servers (combining vs. overriding multiple language server request returns). I'm taking a break from neovim development for the next few months though so I'm not sure what the progress will be.

**Comment by mjlbach** [comment]
> Thank you for the explanation! The requests that we're making here are only supported by a single server, so we don't need to worry about combining and can just send the request to the correct client manually.

Yes, totally. I think lean is more of a unique case (since you are handling this in a plugin). It's more of an issue for users that want to use multiple language servers that might compose (tsserver, cssls, etc.). Happy to discuss API design with you all but I think generally you are probably better served using the lower level requests anyways.

**Comment by rish987** [comment]
Yes sorry I could have gotten on this much sooner. In our implementation we send a request on `BufEnter` or `CursorMoved` after a short delay, which is why this is particularly noticeable.  We could just check `vim.lsp.buf.server_ready()` to early-abort `Pin:__update()` (and possibly even show a "Server connecting..." message) as a quick fix I think. And yes eventually I think we want to move all of our `vim.lsp.buf_request()`s to `client.request()` in anticipation of 0.7.
