### ISSUE TITLE
Lean4 can produce "outdated RPC session" errors from widgets

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#223]
I don't know what I did to get in this situation (if it was just "leave vim open for awhile without interacting"), but I've seen Lean4 produce tooltips that say the RPC session is outdated, and the fix was essentially having to kill the client or vim.

Presumably if there's some session timeout we should be re-establishing the session when this happens?

**Comment by gebner** [comment]
Let me explain the current logic: whenever you update the infoview (by moving the cursor), or execute the `:Lean(Term)Goal` commands, we try to get a valid session id, either by reusing an existing one or opening a new one.  (If we've received an outdated RPC session error, then the corresponding session is marked closed and a new session will be opened the next time.)  This session id is fixed for the entire time the `:Lean(Term)Goal` popup is open, or until the infoview is updated again (by moving the cursor).  The reason is that the shown goal state contains RPC references (=numbers), which are only valid for this specific session id.

A session id becomes invalid if the worker process for the file is restarted.  (E.g. by executing `:e`, or by changing the imports, or because lean crashed.)  (It can also become invalid if we fail to send the keepalive notification, but I doubt that's happening here.)

**Comment by Julian** [comment]
Thanks! Very helpful. I don't know which of those scenarios was involved the time I saw this but will try and see if I can make this happen again.

**Comment by Julian** [comment]
Relatedly (or unrelatedly), I couldn't find a reason to [delay every infoview update](https://github.com/Julian/lean.nvim/commit/7c3e22e61abd9004119f13e7280b2fe95668d779), but now I've found something that doesn't work without it -- namely, when first loading a Lean 4 buffer, if you don't move the cursor in the Lean buffer and then go interact with a widget in the infoview, you can get a:

```json
{
  code = -32602,
  message = "Cannot decode params in RPC call 'Lean.Widget.InteractiveDiagnostics.infoToInteractive({\"p\":\"155\"})'\nRPC reference '155' is not valid",
  <metatable> = {
    __tostring = <function 1>
  }
}
```

Moving the cursor first fixes things, as does putting `util.wait_timer(100)` in `Pin:__update`. It doesn't seem right to wait on every update though, this seems to be some startup related race condition.

**Comment by gebner** [comment]
> namely, when first loading a Lean 4 buffer, if you don't move the cursor in the Lean buffer and then go interact with a widget in the infoview, you can get a:

I cannot reproduce this in the latest main version.  If I open the following file and switch to the infoview without moving the cursor, then I can successfully open the popup on 42:
```lean
#check 42
```

**Comment by Julian** [comment]
Interesting! It only happens on tactic goals.

Try

```
#check 42
example : 2 = 2 := by rfl
```
and compare starting with your cursor over `r`.

**Comment by gebner** [comment]
> Interesting! It only happens on tactic goals.

Okay, I still can't reproduce it.  I've put `rfl` on a new line and ran `nvim +3 test.lean` and widgets still work.

**Comment by Julian** [comment]
Odd. Seems to be a bit non-deterministic though -- here's me doing it 10 times, 2 times work fine, 8 don't:

https://user-images.githubusercontent.com/329822/148658376-19782bdd-c8ba-468a-84b3-883c131f0c00.mov

**Comment by gebner** [comment]
This is certainly super weird.  I first thought this could be because we accidentally restart the Lean server on startup (by accidentally doing something like `:e`).  But then Lean would complain that the RPC session is closed (because we always access RPC objects using the same `sess` object (of type `Subsession`) where we got them from, and the `sess` object contains the session id).

I just see that we're storing the `sess` object as a field in `Pin` now, that's certainly not a good idea (fortunately nothing accesses the field).  `rpc.open` should be called as often as possible (without passing RPC objects from one session to another one), because it will reestablish the connection if necessary.  The name probably doesn't imply it, but `rpc.open` will reuse an already-running session if there is one (so in the common case it's pretty much a hashtable lookup from filename to session object, no LSP requests done).

**Comment by gebner** [comment]
Mmmh, this could also be a race condition in the Lean server code.  https://github.com/leanprover/lean4/blob/1637d75d3f03d9f14595a0f44d691686bd38785f/src/Lean/Server/Rpc/RequestHandling.lean#L47-L68

```lean
    let sesh ← seshRef.get

    let t ← RequestM.asTask -- [decode RPC params]

    let t ← RequestM.bindTask t -- [run RPC function handler]

    RequestM.mapTask t fun
      | Except.error e => throw e
      | Except.ok ret => do
        let act := rpcEncode (α := respType) (β := respLspType) (m := StateM FileWorker.RpcSession) ret
        let (retLsp, sesh') := act.run sesh
        seshRef.set sesh'
```

Reading this correctly, the final `seshRef.set sesh'` will discard all updates that happened in the meantime.  So if we have two concurrent RPC requests, then only one of them will have the RPC references registered.  (And the other one return RPC references that either dangle or point to an incorrect object.)

@vtec234 Is this analysis correct?  Or is there some kind of synchronization that prevents this behavior?

**Comment by Julian** [comment]
Were you able to repro or is it still just me?

**Comment by Julian** [comment]
> I just see that we're storing the sess object as a field in Pin now, that's certainly not a good idea

I haven't refactored much there yet but I'll get there.

**Comment by gebner** [comment]
> Were you able to repro or is it still just me?

I didn't try hard, but if Wojciech confirms my suspicions, then that race condition is the most likely explanation for the bug and also straightforward to fix.

**Comment by Julian** [comment]
> rpc.open should be called as often as possible

45b336e1a2f2a50e2ec6ee8a8c96906113505be5

**Comment by Julian** [comment]
Going to close this now that the upstream PR is merged -- will reopen or something if I can reproduce the original outdated RPC session error. Thanks for diagnosing!
