### ISSUE TITLE
Action to accept lean's suggestion

### ISSUE THREAD

**Issue by yakimk** [Julian/lean.nvim#347]
Didn't find anything concerning accepting lean's suggestions (I mean those popups after `exact?` or `rw?` for instance) . Would be quite handy to bind a shortcut for accepting first suggestion, since clicking on a popup doesn't insert it in place like in vscode and you have to copy it manually. 
Is there any kind of similar functionality that I missed?

**Comment by Julian** [comment]
Hey there!

These are called "code actions" -- and they're not specific to Lean, which is why `lean.nvim` doesn't really handle anything related to them, you just use "normal" neovim ways to activate these.

But, even more specifically -- my intention is to cover this and many other "non-Lean-related" topics in [a new in-progress Manual](https://github.com/Julian/lean.nvim/wiki/The-lean.nvim-Manual#code-actions) -- so I just added the linked section there which should tell you what to touch to get these working.

Can you have a look and let me know if that's specific enough to answer the question here?

**Comment by yakimk** [comment]
Thank you! Exactly what I was looking for.
