### ISSUE TITLE
After a close, infoview no longer auto-opens on new tab.

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#74]
If you've previously closed an infoview and enter a new tab and open a Lean buffer, the infoview doesn't auto-open. TDD test case [here](https://github.com/Julian/lean.nvim/blob/56ec5a746e61a89950f33e5843532eac39f1c5ef/lua/tests/infoview/run_spec.lua#L183).

**Comment by Julian** [comment]
(In my normal use, this is personally expected behavior -- when I close the infoview, by whatever means, it usually means "I don't need interactive lean right now", so it should indeed stop auto-opening, and when I want that again I'd run `.toggle()` to get it back. But I'll review the PR having in mind someone may want the behavior you're proposing).

**Comment by rish987** [comment]
Yep, this is mostly about giving the option. Luckily, you can just hook `set_autoopen(false)` onto whatever trigger you have for `close()` 😉

**Comment by rish987** [comment]
And, this is a bug from your perspective because even if you re-open, it still doesn't auto-open.
