### ISSUE TITLE
Make the builtin abbreviation expansion not insert a space on <tab>

### ISSUE THREAD

**Issue by Julian** [Julian/lean.nvim#83]
The builtin abbreviation expansion inserts a trailing space when hitting both `<Space>` or `<Tab>`.

So `foo x\1<Tab>` expands to `foo x₁ `. This doesn't match my fingers' muscle memory for completion in general, which expect no space there, particularly if I'm inserting something in the middle of an existing line (e.g. in Lean 3 on a line like `foo bar|, baz quux,` where I'm going back to the middle of the line to insert something).

@gebner let me know if you prefer things this way (if so I suppose I can make it configurable)

**Comment by gebner** [comment]
> let me know if you prefer things this way (if so I suppose I can make it configurable)

Yes, I also think that `<tab>` should just expand the abbreviation, without inserting a space.  IIRC, the only reason it inserts a space is because you need to insert *something* when using `inoremap <expr>`.

(Just to be completely clear: typing space should still insert a space, and pressing enter should insert a newline as far as I'm concerned.)
