### ISSUE TITLE
Make unit tests independent from one another (unordered)

### ISSUE THREAD

**Issue by rish987** [Julian/lean.nvim#93]
Generally, the unit tests in a particular `*_spec.lua` file must be run in the particular order given in the file, as subsequent tests may use the state built by previous ones (see esp. `infoview/run_spec.lua`). While I would still consider them unit tests, this makes them a bit less convenient to work with because it forces you to fix failures in a particular order (as failures after the first one may just be a side-effect of previous failures).

If we were to try to handle this at present (without changes to `plenary.nvim`), it seems we would have to either:
1. tear down `nvim` state after every unit test, or
2. put unit tests into separate files so they're run in separate instances,

both of which seem rather unwieldy.

So the best way to go about this seems to be to modify `plenary.nvim` to somehow allow for multiple nvim instances in a single file. This would also allow us to combine our `infoview/*_spec.lua` files into a single file.

Let me know if you have any other ideas!

**Comment by Julian** [comment]
Yeah I briefly was thinking about this too but haven't spent much time trying anything specifically.

The third option (or 2.5th option) is having a bunch of fixtures which set up the state that each test is looking for, but which do so without necessarily saying whether they reuse or redo some state.

Bit hard to describe in text, but in Python the library that does this is e.g. https://pypi.org/project/testresources/ (or https://pypi.org/project/fixtures/ which is roughly the same library).

We could I guess write a simple version for neovim+Lua (and possibly coordinate with @tjdevries or the broader community since it'd be useful beyond just here).

**Comment by Julian** [comment]
Closing this for now as I've done the best I can with some commits -- there's no other low-hanging fruit here that I can see, so we just wait till tooling upstream matures I think rather than futzing too much additionally here.
